name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  Linux:
    name: Ubuntu 22.04
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        compiler: [clang-18, gcc-13]
        build: [Debug, Release]
    env:
      NAME: Linux-${{ matrix.compiler }}-${{ matrix.build }}
      CC: ${{ matrix.compiler }}
      CXX: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v4

    - name: Install prerequisites
      run: |
         wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
         sudo add-apt-repository ppa:ubuntu-toolchain-r/test
         sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main"
         sudo apt update
         sudo apt -y install libgtest-dev liburing-dev libboost-dev g++-13 clang-18
         sudo bash -c "echo 1024 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages"

    - name: CMake tests Linux
      shell: bash
      run:  |
         mkdir build && cd build
         export CXX=${CXX/clang-/clang++-}
         export CXX=${CXX/gcc-/g++-}
         cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build }}
         cmake --build .
         sudo bash -c "ulimit -l 1048576 && ctest -V"
